
require("core.plugin_config.ale")
require("core.plugin_config.autoclose")
require("core.plugin_config.clang-extensions")
require("core.plugin_config.cmp")
require("core.plugin_config.code-runner")
require("core.plugin_config.idl")
require("core.plugin_config.lsp_config")
require("core.plugin_config.lualine")
require("core.plugin_config.luasnip")
require("core.plugin_config.noir-colorscheme")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.web-icons")
